# Generated by Django 5.2 on 2026-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_rename_cgv_to_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms and Conditions'), ('cookies', 'Cookies Policy'), ('legal_mentions', 'Legal Mentions'), ('privacy_policy', 'Privacy Policy')], max_length=20),
        ),
    ]
