# Generated by Django 5.2 on 2026-04-29 07:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=58)),
                ('categorie', models.CharField(choices=[('Hybride', 'Hybride'), ('Macrame', 'Macrame'), ('Maroquinerie', 'Maroquinerie')], max_length=50)),
                ('type', models.CharField(choices=[('Blague à tabac', 'Blague à tabac'), ("Boucles d'oreilles", "Boucles d'oreilles"), ('Bracelet', 'Bracelet'), ('Ceinture', 'Ceinture'), ('Chaine de corps', 'Chaine de corps'), ('Chevillère', 'Chevillère'), ('Collier', 'Collier'), ('Collier chien', 'Collier chien'), ('Divers', 'Divers'), ('Entretien', 'Entretien'), ('Murale', 'Murale'), ('Portefeuille, Porte carte', 'Portefeuille, Porte carte'), ('Sac divers', 'Sac divers')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=135, null=True)),
                ('prix', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('image1', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True)),
                ('image2', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True)),
                ('image3', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True)),
                ('image4', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True)),
                ('image5', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True)),
                ('image6', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('en_attente_dans_panier', models.BooleanField(default=False)),
                ('sur_commande', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
