# Generated by Django 5.2 on 2026-04-29 07:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_migrate_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='product',
            name='en_attente_dans_panier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sur_commande',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hybride', 'Hybride'), ('Macrame', 'Macrame'), ('Maroquinerie', 'Maroquinerie')], default='', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=58, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='on_demand',
            field=models.BooleanField(default=False, verbose_name='Sur commande'),
        ),
        migrations.AddField(
            model_name='product',
            name='pending_in_cart',
            field=models.BooleanField(default=False, verbose_name='En attente dans panier'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Blague à tabac', 'Blague à tabac'), ("Boucles d'oreilles", "Boucles d'oreilles"), ('Bracelet', 'Bracelet'), ('Ceinture', 'Ceinture'), ('Chaine de corps', 'Chaine de corps'), ('Chevillère', 'Chevillère'), ('Collier', 'Collier'), ('Collier chien', 'Collier chien'), ('Divers', 'Divers'), ('Entretien', 'Entretien'), ('Murale', 'Murale'), ('Portefeuille, Porte carte', 'Portefeuille, Porte carte'), ('Sac divers', 'Sac divers')], default='', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0, verbose_name='Remise'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Image 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='Image 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
