# Generated by Django 5.2 on 2026-06-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remigrate_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=135, verbose_name='Description'),
        ),
    ]
