# Generated by Django 5.2 on 2026-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=135, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=135, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='', max_length=58, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(default='', max_length=58, null=True, verbose_name='Nom'),
        ),
    ]
