# Generated by Django 5.2 on 2026-07-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_copy_name_and_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=135, verbose_name='Meta-description'),
        ),
    ]
