# Generated by Django 5.2 on 2026-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.CharField(blank=True, default='', max_length=135, null=True, verbose_name='Meta-description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_fr',
            field=models.CharField(blank=True, default='', max_length=135, null=True, verbose_name='Meta-description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fr',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Description'),
        ),
    ]
