# Generated by Django 5.2 on 2026-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_meta_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hybride', 'Hybride'), ('Macrame', 'Macramé'), ('Maroquinerie', 'Maroquinerie')], default='', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fr',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Nom'),
        ),
    ]
