# Generated by Django 5.2 on 2026-07-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_product_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_ready',
            field=models.BooleanField(default=False, verbose_name='Prêt pour le SEO'),
        ),
    ]
