# Generated by Django 5.2 on 2026-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_h1',
            field=models.CharField(default='', max_length=70, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_h1_en',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_h1_fr',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(default='', max_length=70, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_en',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_fr',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Nom'),
        ),
    ]
