# Generated by Django 5.2 on 2026-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_seo_h1_alter_product_seo_h1_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, max_length=500, verbose_name='Caractéristiques'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fr',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Description'),
        ),
    ]
