# Generated by Django 5.2 on 2026-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_characteristics_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Caractéristiques'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_fr',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Caractéristiques'),
        ),
    ]
