# Generated by Django 5.2 on 2026-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_characteristics_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_h1',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='seo_h1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_h1_en',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='seo_h1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_h1_fr',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='seo_h1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='seo_title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title_en',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='seo_title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title_fr',
            field=models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='seo_title'),
        ),
    ]
