# Generated by Django 5.2 on 2026-04-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0043_allproducts_discount'),
    ]

    operations = [
    ]
    def migrate_cart_cgv(apps, schema_editor):
        Cart = apps.get_model('page_vente', 'Cart')
        CGV = apps.get_model('page_vente', 'CGV')
        LegalDocument = apps.get_model('legal', 'LegalDocument')

        for cart in Cart.objects.filter(cgv_accepted__isnull=False):
            old_cgv = CGV.objects.get(pk=cart.cgv_accepted_id)
            new_doc = LegalDocument.objects.get(
                document_type='terms',
                version=old_cgv.version
            )
            cart.cgv_accepted = new_doc
            cart.save()