# Generated by Django 5.2 on 2026-04-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_alter_legaldocument_document_type'),
        ('page_vente', '0043_allproducts_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cgv_accepted_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legal.legaldocument'),
        ),
    ]
