# Generated by Django 5.2 on 2026-04-04 07:28

from django.db import migrations


def migrate_cgv(apps, schema_editor):
    Cart = apps.get_model('page_vente', 'Cart')
    LegalDocument = apps.get_model('legal', 'LegalDocument')

    for cart in Cart.objects.filter(cgv_accepted__isnull=False):
        legal_doc = LegalDocument.objects.filter(
            document_type='terms',
            version=cart.cgv_accepted.version
        ).first()
        if legal_doc:
            cart.cgv_accepted_new = legal_doc
            cart.save()

class Migration(migrations.Migration):
    dependencies = [('page_vente', '0044_cart_cgv_accepted_new')]
    operations = [migrations.RunPython(migrate_cgv)]