# Generated by Django 5.2 on 2026-04-04 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_alter_legaldocument_document_type'),
        ('page_vente', '0045_migrate_cart_cgv_to_legal_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cgv_accepted_new',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cgv_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='legal.legaldocument'),
        ),
    ]
