# Generated by Django 5.2 on 2026-04-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0046_remove_cart_cgv_accepted_new_alter_cart_cgv_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CGV',
        ),
        migrations.DeleteModel(
            name='CookiesPolicy',
        ),
        migrations.DeleteModel(
            name='LegalMention',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
