# Generated by Django 5.2 on 2026-04-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_alter_legaldocument_document_type'),
        ('page_vente', '0047_delete_cgv_delete_cookiespolicy_delete_legalmention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cgv_accepted',
            field=models.ForeignKey(limit_choices_to={'document_type': 'terms'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='legal.legaldocument'),
        ),
    ]
