# Generated by Django 5.2 on 2026-05-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_vente', '0048_alter_cart_cgv_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cgv_accepted',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='AllProducts',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
