name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SQLITE_URL: ${{ secrets.SQLITE_URL }}
  DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
  DEBUG: ${{ secrets.DEBUG }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    - name: Run Tests
      run: pytest -v
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Deploy to PythonAnywhere
      run: |
        # Git pull
        curl -s -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/consoles/" -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}" -d "executable=bash&arguments=-c 'cd leatherwork-in-traveling-db && git pull && source ~/.virtualenvs/leatherwork/bin/activate && pip install -r requirements/base.txt && python manage.py migrate && python manage.py collectstatic --noinput'"
        # Reload
        curl -s -X POST "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PYTHONANYWHERE_USERNAME }}/webapps/${{ secrets.PYTHONANYWHERE_USERNAME }}.pythonanywhere.com/reload/" -H "Authorization: Token ${{ secrets.PYTHONANYWHERE_API_TOKEN }}"
